version: "3.2"

services:

  ################ JENKINS #################################
  master:
    image: vfarcic/jenkins:scale
    ports:
      - 50000:50000
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
      - VIRTUAL_HOST=jenkinsMaster.jenkins
    #networks:
    #   - proxy
    #  - default
    #   - monitor
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/jenkins
        - com.df.port=8080
      resources:
        reservations:
          memory: 600M
        limits:
          memory: 800M
    secrets:
      - jenkins-user
      - jenkins-pass

  agent:
    image: vfarcic/jenkins-swarm-agent:19.03.15-2
    environment:
      - USER_NAME_SECRET=/run/secrets/${JENKINS_USER_SECRET:-jenkins-user}
      - PASSWORD_SECRET=/run/secrets/${JENKINS_PASS_SECRET:-jenkins-pass}
      - COMMAND_OPTIONS=-master http://master:8080/jenkins -labels 'prod' -executors 2
      - VIRTUAL_HOST=jenkins.jenkins
    # networks:
    #   - proxy
    #   - default
    #   - monitor
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - ../resolv.conf:/etc/resolv.conf
    secrets:
      - jenkins-user
      - jenkins-pass
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          memory: 150M
        limits:
          memory: 300M


  ################ PROXY #################################
  proxy:
    image: dockerflow/docker-flow-proxy:${TAG:-latest}
    ports:
      - 80:80
      - 443:443
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
      - CONNECTION_MODE=${CONNECTION_MODE:-http-server-close}
      - STATS_USER=admin
      - STATS_PASS=admin
    deploy:
      resources:
        reservations:
          memory: 10M
        limits:
          memory: 20M


  ################ SCRAPERS #################################
  ha-proxy:
    image: quay.io/prometheus/haproxy-exporter:${HA_PROXY_TAG:-latest}
    # networks:
    #   - proxy
    #   - monitor
    ports:
      - 9101:9101
    deploy:
      labels:
        - com.df.notify=true
        - com.df.scrapePort=9101
    command: --haproxy.scrape-uri="http://admin:admin@proxy/admin?stats;csv"


  cadvisor:
    image: google/cadvisor
    # networks:
    #   - monitor
    ports:
      - 9102:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    deploy:
      mode: global
      labels:
        - com.df.notify=true
        - com.df.scrapePort=8080


  node-exporter:
    image: basi/node-exporter
    # networks:
    #   - monitor
    environment:
      - HOST_HOSTNAME=/etc/host_hostname
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/host_hostname
    ports:
      - 9103:9100
    deploy:
      mode: global
      labels:
        - com.df.notify=true
        - com.df.scrapePort=9100
        
        - com.df.alertName.1=mem_load
        - com.df.alertIf.1=(sum by (instance) (node_memory_MemTotal) - sum by (instance) (node_memory_MemFree + node_memory_Buffers + node_memory_Cached)) / sum by (instance) (node_memory_MemTotal) > 0.8

        - com.df.alertName.2=disk_load
        - com.df.alertIf.2=@node_fs_limit:0.8

        - com.df.alertName.3=http_req_load
        - com.df.alertIf.3=(avg(http_requests_total[5m]) by (application)) > 10

    command: '--path.procfs="/host/proc" --path.sysfs="/host/sys" --collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)" --collector.textfile.directory="/etc/node-exporter/" --collector.conntrack --collector.diskstats --collector.entropy --collector.filefd --collector.filesystem --collector.loadavg --collector.mdadm --collector.meminfo --collector.netdev --collector.netstat --collector.stat --collector.textfile --collector.time --collector.vmstat --collector.ipvs'


  ################ PROMETHEUS #################################
  monitor:
    image: dockerflow/docker-flow-monitor
    environment:
      - VIRTUAL_HOST=monitor.local
      - LISTENER_ADDRESS=swarm-listener
      - GLOBAL_SCRAPE_INTERVAL=${SCRAPE_INTERVAL:-10s}
      - ARG_WEB_ROUTE-PREFIX=/monitor
      - ARG_WEB_EXTERNAL-URL=http://${DOMAIN:-localhost}/monitor
      - ARG_ALERTMANAGER_URL=http://alert-manager:9093
    # networks:
    #   - proxy
    #   - monitor
    ports:
      - 9090:9090
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/monitor
        - com.df.serviceDomain=${DOMAIN:-localhost}
        - com.df.port=9090
      resources:
        reservations:
          memory: 500M
        limits:
          memory: 800M


  alert-manager:
    image: prom/alertmanager
    # networks:
    #   - monitor
    secrets:
      - alert_manager_config
    depends_on:
      - cadvisor
    command: --config.file=/run/secrets/alert_manager_config --storage.path=/alertmanager


  swarm-listener:
    image: dockerflow/docker-flow-swarm-listener
    # networks:
    #   - monitor
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://monitor:8080/v1/docker-flow-monitor/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://monitor:8080/v1/docker-flow-monitor/remove
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          memory: 5M
        limits:
          memory: 10M


networks:
  monitor:
    external: true
  proxy:
    external: true
  default:


secrets:
  alert_manager_config:
    external: true

  jenkins-user:
    external: true
  jenkins-pass:
    external: true
